name: dev_toast
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.11.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  dev_toast_platform_interface:
    path: ./dev_toast_platform_interface

  dev_toast_web:
    path: ./dev_toast_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.dev_toast
        pluginClass: DevToastPlugin
      windows:
        #        pluginClass: DevToastPluginCApi using dart instead
        pluginClass: DevToastWindows
        filename: src/dev_toast_windows.dart
