name: dev_toast_web
description: "The web implementation of the dev_toast plugin."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  dev_toast_platform_interface: ^0.0.1
#    path: ../dev_toast_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: dev_toast
    platforms:
      web:
        pluginClass: DevToastWeb
        fileName: dev_toast_web.dart
